API_KEY = "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"
GOLDEN_ANSWERS = "golden_answers.txt"
RAG_doc="e_commerce_RAG_doc.txt"